{
	"version": 1527368526,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/smonstrobaixo-sheet0.png",
		"images/splayer-sheet0.png",
		"images/splayer-sheet1.png",
		"images/splayer-sheet2.png",
		"images/splayercima-sheet0.png",
		"images/splayercima-sheet1.png",
		"images/splayercima-sheet2.png",
		"images/bbaixo-sheet0.png",
		"images/bcima-sheet0.png",
		"images/besquerda-sheet0.png",
		"images/bdireita-sheet0.png",
		"images/sbarra-sheet0.png",
		"images/schaveicone-sheet0.png",
		"images/fxluzmapa-sheet0.png",
		"images/fxluzplayer-sheet0.png",
		"images/slight_refil-sheet0.png",
		"images/slight_refil-sheet1.png",
		"images/sparede-sheet0.png",
		"images/sparede-sheet1.png",
		"images/sparede-sheet2.png",
		"images/sporta-sheet0.png",
		"images/sporta-sheet1.png",
		"images/schave-sheet0.png",
		"images/fxloading-sheet0.png",
		"images/fxloading-sheet1.png",
		"images/fxbkgjumpscare-sheet0.png",
		"images/fxjumpscare-sheet0.png",
		"images/fxjumpscare-sheet1.png",
		"images/fxjumpscare-sheet2.png",
		"images/textbackground-sheet0.png",
		"images/bkgcreditos-sheet0.png",
		"images/balterarmusica-sheet0.png",
		"images/balterarmusica-sheet1.png",
		"images/balterarsfx-sheet0.png",
		"images/balterarsfx-sheet1.png",
		"images/bcreditos-sheet0.png",
		"images/bnewgame-sheet0.png",
		"images/info-sheet0.png",
		"images/iinformação-sheet0.png",
		"images/ilogo-sheet0.png",
		"images/fxfademenu-sheet0.png",
		"images/bvoltar-sheet0.png",
		"images/bkggameover-sheet0.png",
		"images/ilogoempresa-sheet0.png",
		"images/fxlogobackground-sheet0.png",
		"images/tbchao.png",
		"images/bkgvitoria-sheet0.png",
		"media/paços (opcional).ogg",
		"media/ao clicar nos botoes.m4a",
		"media/ao clicar nos botoes.ogg",
		"media/reversed.m4a",
		"media/reversed.ogg",
		"media/horror cinema 7 2014(tela splash).m4a",
		"media/horror cinema 7 2014(tela splash).ogg",
		"media/radio_death.m4a",
		"media/radio_death.ogg",
		"media/collectable chave.m4a",
		"media/collectable chave.ogg",
		"media/collectables.m4a",
		"media/collectables.ogg",
		"media/ancient apparitions (jogo normal).ogg",
		"media/haunted woods loop (home screen).m4a",
		"media/haunted woods loop (home screen).ogg",
		"media/sinkingisland (creditos - info).ogg",
		"media/horror_effect1 (perseguicao do monstro).m4a",
		"media/horror_effect1 (perseguicao do monstro).ogg",
		"media/unforgiving lands (vitoria).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png",
		"pathfind.js"
	]
}